### ISSUE TITLE
No working bro

### ISSUE THREAD

**Issue by DANGERHACKER007** [OnlineHacKing/FreeFire-Phishing#10]
![Screenshot_2021-08-22-14-09-08-601_com.termux.jpg](https://user-images.githubusercontent.com/88316000/130348576-f84bbfff-85e0-4ab3-a5d9-83680fd175be.jpg)

**Comment by OnlineHacKing** [comment]
Android setup not complete

**Comment by DANGERHACKER007** [comment]
Ok

**Comment by DANGERHACKER007** [comment]
Please help me

**Comment by DANGERHACKER007** [comment]
Bro command kiya hai

**Comment by DANGERHACKER007** [comment]
Thanks bro

**Comment by Kuttiram007** [comment]
Bro Key website is not opening please help me bro

**Comment by OnlineHacKing** [comment]
Play video tutorial

**Comment by Kamanati** [comment]
Bro I have created free fire phishing tool that is in
`https://github.com/kamanati/zphisher`
I added FFreward in this zphisher tool

**Comment by Kamanati** [comment]
> ![Screenshot_2021-08-22-14-09-08-601_com.termux.jpg](https://user-images.githubusercontent.com/88316000/130348576-f84bbfff-85e0-4ab3-a5d9-83680fd175be.jpg)

Bro I can help you you need free fire phishing  then I can help you  you install my tool that's I created 
```
- https://github.com/kamanati/zphisher
![Screenshot_20220522-075928_Termux](https://user-images.githubusercontent.com/98698457/169675737-6a1b9f3f-7377-4637-a989-5afc37cf5a32.png)

```
Here I added FFreward,FFlucky,FFpricr,etc...
```

**Comment by OnlineHacKing** [comment]
Update new version
