### ISSUE TITLE
Bro Key website is not opening please help me bro

### ISSUE THREAD

**Issue by Kuttiram007** [OnlineHacKing/FreeFire-Phishing#25]
https://tinyurl.com/FreeFire-Key

**Comment by Kamanati** [comment]
Bro I have created  free fire phishing  tool that is in 
`https://github.com/kamanati/zphisher`
I added FFreward in this zphisher  tool

**Comment by Kamanati** [comment]
Bro use this tool it will help you

**Comment by OnlineHacKing** [comment]
Tools and Website updae chack again
