### ISSUE TITLE
Please send me 1000 Diamonds Please I am sending to my friends and I telling install and we will play I told then they installed  so I am requesting you please send me diamonds my id 4393875007 please 

### ISSUE THREAD

**Issue by 43182** [OnlineHacKing/FreeFire-Phishing#32]
Please send me 1000 Diamonds Please I am sending to my friends and I telling install and we will play I told then they installed  so I am requesting you please send me diamonds my id 4393875007 please

**Comment by OnlineHacKing** [comment]
scam
