### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chhassan0x** [OnlineHacKing/FreeFire-Phishing#41]
I want to know activation code. Plz help
![Screenshot_2023-01-01-21-56-13-178_com termux](https://user-images.githubusercontent.com/121739427/210178993-550290ba-c4b5-4eab-9de2-e9138f246147.jpg)

**Comment by karanrockstar** [comment]
Hello sir

**Comment by OnlineHacKing** [comment]
Enter key. click this link and create key
