### ISSUE TITLE
> Bangladesh sarver 

### ISSUE THREAD

**Issue by majdulislammomin** [OnlineHacKing/FreeFire-Phishing#7]
> Bangladesh sarver 

https://github.com/OnlineHacKing/FreeFire-Phishing/pull/6#issue-696081478

_Originally posted by @majdulislammomin in https://github.com/OnlineHacKing/FreeFire-Phishing/issues/6#issuecomment-885775334_

**Comment by RakiBULnn** [comment]
Free 100℅

**Comment by RakiBULnn** [comment]
Success

**Comment by RakiBULnn** [comment]
Leave

**Comment by Pksamyjlsbskbd** [comment]
Pro enaku link anupuga hack link
