### ISSUE TITLE
Unable to generate link

### ISSUE THREAD

**Issue by fgabcy** [OnlineHacKing/FreeFire-Phishing#8]
Despite following the video instructions. I were unable to generate phish links.
Is there anything missing out? I turn on mobile data and also tried it on WiFi.![SmartSelect_20210724-163811_Termux.jpg](https://user-images.githubusercontent.com/66316052/126873604-9a8f7047-2964-46b1-bb1c-dd5b0f4402a2.jpg)

**Comment by Devipoovarasan** [comment]
Nice

**Comment by OnlineHacKing** [comment]
tool is update install new versions and hack again
